#include "block.h"

extern inline block192 block192_xor(block192 x, block192 y);
extern inline block192 block192_and(block192 x, block192 y);
extern inline block192 block192_set_all_8(uint8_t x);
extern inline block192 block192_set_low64(uint64_t x);
extern inline block192 block192_set_low32(uint32_t x);
extern inline block192 block192_set_zero();
extern inline block_secpar block_secpar_xor(block_secpar x, block_secpar y);
extern inline block_secpar block_secpar_and(block_secpar x, block_secpar y);
extern inline block_secpar block_secpar_set_all_8(uint8_t x);
extern inline block_secpar block_secpar_set_low32(uint32_t x);
extern inline block_secpar block_secpar_set_low64(uint64_t x);
extern inline block_secpar block_secpar_set_zero();
extern inline bool block_secpar_any_zeros(block_secpar x);
extern inline block_2secpar block_2secpar_xor(block_2secpar x, block_2secpar y);
extern inline block_2secpar block_2secpar_and(block_2secpar x, block_2secpar y);
extern inline block_2secpar block_2secpar_set_all_8(uint8_t x);
extern inline block_2secpar block_2secpar_set_low32(uint32_t x);
extern inline block_2secpar block_2secpar_set_low64(uint64_t x);
extern inline block_2secpar block_2secpar_set_zero();
extern inline block_secpar block_secpar_xor(block_secpar x, block_secpar y);
extern inline block_secpar block_secpar_and(block_secpar x, block_secpar y);
extern inline block_secpar block_secpar_set_all_8(uint8_t x);
extern inline block_secpar block_secpar_set_low32(uint32_t x);
extern inline block_secpar block_secpar_set_low64(uint64_t x);
extern inline block_secpar block_secpar_set_zero();
extern inline bool block_secpar_any_zeros(block_secpar x);
extern inline block_2secpar block_2secpar_xor(block_2secpar x, block_2secpar y);
extern inline block_2secpar block_2secpar_and(block_2secpar x, block_2secpar y);
extern inline block_2secpar block_2secpar_set_all_8(uint8_t x);
extern inline block_2secpar block_2secpar_set_low32(uint32_t x);
extern inline block_2secpar block_2secpar_set_low64(uint64_t x);
extern inline block_2secpar block_2secpar_set_zero();
extern inline block_secpar block_secpar_xor(block_secpar x, block_secpar y);
extern inline block_secpar block_secpar_and(block_secpar x, block_secpar y);
extern inline block_secpar block_secpar_set_all_8(uint8_t x);
extern inline block_secpar block_secpar_set_low32(uint32_t x);
extern inline block_secpar block_secpar_set_low64(uint64_t x);
extern inline block_secpar block_secpar_set_zero();
extern inline bool block_secpar_any_zeros(block_secpar x);
extern inline block_2secpar block_2secpar_xor(block_2secpar x, block_2secpar y);
extern inline block_2secpar block_2secpar_and(block_2secpar x, block_2secpar y);
extern inline block_2secpar block_2secpar_set_all_8(uint8_t x);
extern inline block_2secpar block_2secpar_set_low32(uint32_t x);
extern inline block_2secpar block_2secpar_set_low64(uint64_t x);
extern inline block_2secpar block_2secpar_set_zero();
