/* This file is autogenerated by ./configure -- do not edit! */
#define FLINT_USES_POPCNT
#define FLINT_USES_BLAS 0
#define FLINT_USES_TLS 1
#define FLINT_USES_FENV 1
#define FLINT_USES_PTHREAD 1
#define FLINT_BIG_ENDIAN 0
#define FLINT_USES_GC 0
#define FLINT_USES_CPUSET 1
#define FLINT_REENTRANT 0
#define FLINT_WANT_ASSERT 0
#define FLINT_DLL
